# ----
# Site

title: Ghibli API
description: Ghibli API documentation.
url: https://jamesanaipakos.com/ghibli-api
google_analytics_key:
permalink: pretty

collections:
  documentation:
    title: Documentation
    position: 1
  api:
    title: APIs
    position: 2
gems:
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - readme.md
  - LICENCE

defaults:
  -
    scope:
      path: ""
    values:
      layout: default

types:
  - get
